import { Transform } from 'class-transformer';

/**
 * Reads a money amount typed by a person, not generated by a machine.
 *
 * A salary box invites grouping separators — "24,00,000" in India, "2 400 000"
 * in much of Europe, "2,400,000" elsewhere — and `Number()` turns every one of
 * them into `NaN`. The field then fails with "must be a number", which tells
 * the candidate nothing about what they did wrong.
 *
 * So spaces and commas are removed before the number is read.
 *
 * THE GUESS THIS MAKES, stated plainly: a comma is treated as a grouping
 * separator, never a decimal point. "1,5" is fifteen here, though a German
 * speaker means one and a half. That is a real wrong answer, accepted because
 * the alternative — inferring the locale from a request — is a worse guess,
 * and because the field it serves is an annual salary alongside an explicit
 * currency picker, where fractions do not arise and grouping always does.
 *
 * Use this only for amounts a person types. Codes come from dropdowns and
 * should keep failing loudly if they arrive malformed — see ToOptionalNumber.
 */
export function ToOptionalAmount(): PropertyDecorator {
  return Transform(({ obj, key }: { obj: unknown; key: string }): unknown => {
    const raw = (obj as Record<string, unknown>)[key];

    if (raw === undefined || raw === null) return undefined;
    if (typeof raw === 'number') return raw;
    if (typeof raw !== 'string') return raw;

    const cleaned = raw.replace(/[\s,]/g, '');
    if (cleaned === '') return undefined;

    // A non-numeric remainder becomes NaN, which @IsNumber then rejects with
    // its own message — which is what should happen to "about 20 lakh".
    return Number(cleaned);
  });
}
